[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["/server/**"]

[deploy]

preDeployCommand = ["flask --app run init-db"]

healthcheckPath = "/api/health"
healthcheckTimeout = 60

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
