[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["/server/**"]

[deploy]
startCommand = "flask --app run crawl-daily"
cronSchedule = "0 19 * * *"
restartPolicyType = "NEVER"
