ALTER TABLE users
  ADD COLUMN username VARCHAR(20) NOT NULL DEFAULT '' AFTER id,
  ADD COLUMN avatar   MEDIUMTEXT NULL AFTER nickname,
  MODIFY COLUMN email    VARCHAR(255) NULL,
  MODIFY COLUMN nickname VARCHAR(50)  NOT NULL DEFAULT '';

ALTER TABLE users
  ADD UNIQUE KEY uq_users_username (username);
