CREATE TABLE IF NOT EXISTS singer_alias (
  alias_norm VARCHAR(120) NOT NULL PRIMARY KEY,
  singer     VARCHAR(255) NOT NULL,
  hits       INT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
